Primer entregable parte 1
jgallego25/BAZANDROID4-2023CAPSTONE pull request #1
Opened 2023-04-03 22:09 UTC by jgallego25

- consumir end point movie/now_playing y mostrar peliculas
- crear interceptor para mandar apikey
- crear base de datos en room

2023-04-03 23:18 UTC, sacastrillon requested changes
Recuerda partir los PR en partes más pequeñas para facilitar la revisión.

2023-04-03 23:18 UTC, sacastrillon commented on app/src/main/java/com/example/themoviedb/MainActivity.kt
> +package com.example.themoviedbimport androidx.appcompat.app.AppCompatActivityimport android.os.Bundleimport androidx.navigation.fragment.NavHostFragmentimport androidx.navigation.ui.setupWithNav
no estoy seguro porque tiene mala la indentación ésta clase. Podrías revisarla?

2023-04-03 23:18 UTC, sacastrillon commented on app/src/main/java/com/example/themoviedb/binding/BindingAdapters.kt
> +fun setImageUrl(imageView: AppCompatImageView, url: String?) {
estas usando glide para cargar las imágenes? si no lo necesitas mejor lo eliminamos por ahora

2023-04-03 23:18 UTC, sacastrillon commented on app/src/main/java/com/example/themoviedb/data/datasource/local/LatestLocal.kt
> +            imageUrl = "https://image.tmdb.org/t/p/w500/".plus(it.posterPath)
Creo que podrías definir esta `BaseURL` como constante dado que se repite en varias partes

2023-04-03 23:18 UTC, sacastrillon commented on app/src/main/java/com/example/themoviedb/data/datasource/local/NowPlayingLocal.kt
> +fun List<NowPlayingLocal>.toModel(): List<MovieModel> {
es posible usar una sola fun extension? se repite en `app/src/main/java/com/example/themoviedb/data/datasource/local/LatestLocal.kt`

2023-04-03 23:18 UTC, sacastrillon commented on app/src/main/java/com/example/themoviedb/data/datasource/local/TopRatedLocal.kt
> +fun List<TopRatedLocal>.toModel(): List<MovieModel> {
Se repite en `app/src/main/java/com/example/themoviedb/data/datasource/local/LatestLocal.kt` y `app/src/main/java/com/example/themoviedb/data/datasource/local/NowPlayingLocal.kt`

2023-04-03 23:18 UTC, sacastrillon commented on app/src/main/java/com/example/themoviedb/data/datasource/remote/MovieRemoteDataSourceImpl.kt
> +        return APIServiceAutoBuilder.safeApiCall(Dispatchers.IO) {
`Dispatchers.IO` no es necesario definirlo en todas las llamadas dado que siempre se hacen en IO thread

2023-04-03 23:18 UTC, sacastrillon commented on app/src/main/java/com/example/themoviedb/data/repository/MovieRepositoryImpl.kt
> +        withContext(Dispatchers.IO) {
Se puede omitir `Dispatchers.IO` para estas funciones

2023-04-03 23:18 UTC, sacastrillon commented on app/src/main/java/com/example/themoviedb/data/repository/MovieRepositoryImpl.kt
> +                if (it is ResultWrapper.Success) {
Podríamos incorporar el caso de error en la respuesta para que sea mostrado al usuario

2023-04-03 23:18 UTC, sacastrillon commented on app/src/main/java/com/example/themoviedb/network/APIServiceAutoBuilder.kt
> +                    .addInterceptor(ApiKeyInterceptor("61d7cb2732da6def41add30787cfd905"))
Definamos el API key en el archivo `local.properties` puedes usar esta documentación https://guides.codepath.com/android/storing-secret-keys-in-android

2023-04-03 23:18 UTC, sacastrillon commented on app/src/main/java/com/example/themoviedb/network/APIServiceAutoBuilder.kt
> +                            ResultWrapper.Error(0, "")
Retornemos un default error "Something went wrong" para éste caso

2023-04-06 15:17 UTC, jgallego25 commented on app/src/main/java/com/example/themoviedb/MainActivity.kt
> +package com.example.themoviedbimport androidx.appcompat.app.AppCompatActivityimport android.os.Bundleimport androidx.navigation.fragment.NavHostFragmentimport androidx.navigation.ui.setupWithNav
se arreglo configurando los saltos de linea

2023-04-06 15:18 UTC, jgallego25 commented on app/src/main/java/com/example/themoviedb/binding/BindingAdapters.kt
> +fun setImageUrl(imageView: AppCompatImageView, url: String?) {
Se usa binding adapter en xml

2023-04-06 15:19 UTC, jgallego25 commented on app/src/main/java/com/example/themoviedb/data/datasource/local/LatestLocal.kt
> +            imageUrl = "https://image.tmdb.org/t/p/w500/".plus(it.posterPath)
Se arregla en el siguiente commit

2023-04-06 15:20 UTC, jgallego25 commented on app/src/main/java/com/example/themoviedb/data/datasource/local/NowPlayingLocal.kt
> +fun List<NowPlayingLocal>.toModel(): List<MovieModel> {
se removieron en el siguiente commit

2023-04-06 15:20 UTC, jgallego25 commented on app/src/main/java/com/example/themoviedb/data/datasource/local/TopRatedLocal.kt
> +fun List<TopRatedLocal>.toModel(): List<MovieModel> {
se arreglo en sig commit

2023-04-06 15:21 UTC, jgallego25 commented on app/src/main/java/com/example/themoviedb/data/datasource/remote/MovieRemoteDataSourceImpl.kt
> +        return APIServiceAutoBuilder.safeApiCall(Dispatchers.IO) {
se configuro un dispatcher default

2023-04-06 15:22 UTC, jgallego25 commented on app/src/main/java/com/example/themoviedb/data/repository/MovieRepositoryImpl.kt
> +        withContext(Dispatchers.IO) {
se resolvio en el sig commit

2023-04-06 15:22 UTC, jgallego25 commented on app/src/main/java/com/example/themoviedb/data/repository/MovieRepositoryImpl.kt
> +                if (it is ResultWrapper.Success) {
se arreglo en el sig commit

2023-04-06 15:22 UTC, jgallego25 commented on app/src/main/java/com/example/themoviedb/network/APIServiceAutoBuilder.kt
> +                            ResultWrapper.Error(0, "")
se cambio el mensaje

2023-04-06 15:24 UTC, jgallego25 commented on app/src/main/java/com/example/themoviedb/network/APIServiceAutoBuilder.kt
> +                    .addInterceptor(ApiKeyInterceptor("61d7cb2732da6def41add30787cfd905"))
se paso a local properties

2023-04-10 20:26 UTC, closed without merging